# Generated by Django 2.1.5 on 2019-01-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='文章标题')),
                ('txt', models.TextField(verbose_name='文章内容')),
                ('num_read', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='阅读量')),
                ('num_like', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='点赞量')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='create_time')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='update_time')),
            ],
            options={
                'verbose_name': '文章信息',
                'verbose_name_plural': '文章信息',
            },
        ),
    ]
